---
name: Bug Report
title: "Bug Report: CHANGEME"
labels: bug_report
assignees: zontreck
body:
- type: textarea
  attributes:
    label: "What I was doing when this happened"
- type: textarea
  attributes:
    label: "What steps will reproduce the bug?"
- type: textarea
  attributes:
    label: "What I was expecting to happen"
- type: textarea
  attributes:
    label: "What actually happened"
---